### ISSUE TITLE
Cheesemod patch not detecting Cheesemod as supported mod

### ISSUE THREAD

**Issue by Jragghen** [Ic0nic0de/TheCuratorsCompanion#14]
Hey - love the mod and have been using it for a good bit. I updated to the latest version, and noticed Cheesemod wasn't present in the supported mods list (one of the CC mods I'd gotten since the previous update was added without issue). I've read the Article, think I've done everything right (save is since 3.0.0, regardless), and did some further testing in a new profile: the same problem occurs on a brand new save, with only Cheesemod, LOTD, and TCC (and SkyUI, moreHUD, FISSES, etc) enabled. Additionally, I re-installed TCC in a separate folder with just Cheesemod included, same deal - looks like something isn't getting hooked up right to detect that Cheesemod is available as an option.

While I was doing this checking, I found two other things with the FOMOD, fyi - Dwemer Spectres and Teldryn Serious both detect as installed, despite their parent mods not being enabled (might just be looking for the DBM_* esps from LOTD patches, but none of the other patches exhibited this behavior). 

A couple quick screenshots:

https://imgur.com/a/LqT3jf2

Thanks!

**Comment by Ic0nic0de** [comment]
Cheesemod does not show in the supported mods list as they are not proper displays that are monitored, they are just generic safehouse items, if you have safehouse integration on and cheesemod installed then everything is working fine, also most of the more recent patches just check that the DBM patch is installed and enabled in the load order, not every single master.
