### ISSUE TITLE
Cheesemod patch not working

### ISSUE THREAD

**Issue by bathhousecitron** [Ic0nic0de/TheCuratorsCompanion#15]
See title. The mod installer does not recognize Cheesemod when it's installed. Manually enabling the plugin doesn't work: it does not appear under the Supported Mods section on the MCM, and the new UI icons aren't added to any of the cheeses.

**Comment by Ic0nic0de** [comment]
You need to install the Legacy patch from the official patches FOMOD before trying to install the TCC patch, also the mod appears in the MCM under the "moreHUD & Scan" page along with safehouse plus.

**Comment by bathhousecitron** [comment]
The Legacy patch *is* installed, and there's no mention to Cheesemod anywhere in the moreHUD page.

**Comment by Ic0nic0de** [comment]
Install legacy patch, install TCC patch, enable safehouse integration in the MCM, Done.
