### ISSUE TITLE
Cheese storage crate not in Cheese aging room

### ISSUE THREAD

**Issue by diegantobass** [Ic0nic0de/TheCuratorsCompanion#16]
I am using legacy of the dragonborn 5.4.4 with official patches 2.4.1. I have installed your mod mid game with patch for the Cheese for everyone mod (delicious!) but it has made my Cheese Storage Crate disappear from the Cheese aging room in the Safehouse.

Respawning the crate with console and reattaching the script from DBM_YUMCheeseStorageCrateScript to it does nothing. The scripts don't fire and the cheese are not displaying on the shelves.

I have included my load order and my specs in this reddit post : https://www.reddit.com/r/skyrimmods/comments/kmbdv0/help_needed_my_safehouse_cheese_aging_room/

Any help greatly appreciated. I am french, I can't do without the cheese. Thank you very much for your mod and in advance for your help.

**Comment by diegantobass** [comment]
I realize now that I should have a menu entry for Cheese mod in my MCM because you actually added support for Cheese mod. I don't ! That's definitely linked to the problem.

**Comment by Ic0nic0de** [comment]
Non Issue
