### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by bowem9** [Ic0nic0de/TheCuratorsCompanion#17]
Whenever I try to save or fast travel after setting up the mod my game crashes to desktop. I didn't have this problem last time I installed this addon on my old computer.
EDIT: After disabling the mod which I assume would be safe given that it never really set up in my game. I'm still crashing. Even if I load a save from before I downloaded the mod. This wasn't happening until I installed the mod.

Here's my load order in case it might illuminate something I'm not aware of.

 0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
254 FE   0 ccbgssse002-exoticarrows.esl
254 FE   1 ccbgssse003-zombies.esl
254 FE   2 ccbgssse004-ruinsedge.esl
254 FE   3 ccbgssse006-stendarshammer.esl
254 FE   4 ccbgssse010-petdwarvenarmoredmudcrab.esl
254 FE   5 ccbgssse019-staffofsheogorath.esl
254 FE   6 ccqdrsse001-survivalmode.esl
254 FE   7 ccqdrsse002-firewood.esl
254 FE   8 ccbgssse018-shadowrend.esl
254 FE   9 ccfsvsse001-backpacks.esl
254 FE   a ccbgssse037-curios.esl
254 FE   b ccmtysse002-ve.esl
254 FE   c ccbgssse040-advobgobs.esl
254 FE   d ccbgssse058-ba_steel.esl
254 FE   e ccpewsse002-armsofchaos.esl
254 FE   f ccedhsse002-splkntset.esl
254 FE  10 ccbgssse063-ba_ebony.esl
254 FE  11 ccbgssse060-ba_dragonscale.esl
254 FE  12 ccbgssse057-ba_stalhrim.esl
  5  5     ccbgssse025-advdsgs.esm
  6  6     Unofficial Skyrim Special Edition Patch.esp
  7  7     LegacyoftheDragonborn.esm
  8  8     BSAssets.esm
  9  9     BSHeartland.esm
 10  a     FISS.esp
 11  b     BS_DLC_patch.esp
 12  c     Midwood Isle.esp
 13  d     DBM_CC_HallOfWonders.esp
254 FE  13 DBM_CC_SurvivalHOWPatch.esp
           AHZmoreHUDInventory.esl
 14  e     SkyUI_SE.esp
 15  f     Dolomite Weathers.esp
254 FE  14 DBM_CC_HOWTemperingEnabler.esp
 16 10     Castle Volkihar Rebuilt.esp
 17 11     Volkihar Knight.esp
 18 12     The Great Cities - Minor Cities and Towns.esp
 19 13     Civil War Aftermath.esp
254 FE  15 radiantBlocker.esp
 20 14     LCO_Framework.esp
 21 15     Faction Economy - Complete.esp
 22 16     Undeath.esp
 23 17     LCO_AllInOne.esp
 24 18     Settlements Expanded SE.esp
 25 19     Man Those Borders!.esp
 26 1a     CivilWarCheckpointsV2 .esp
 27 1b     Better Vampire NPCs.esp
 28 1c     DIVERSE SKYRIM.esp
 29 1d     OBIS SE.esp
 30 1e     DBM_RelicNotifications.esp
254 FE  16 DBM_CC_RareCuriosHOWPatch.esp
254 FE  17 LOTD_TCC_RareCurios.esp
254 FE  18 DBM_OBIS_Patch.esp
 31 1f     Wintersun - Faiths of Skyrim.esp
 32 20     Immersive Encounters.esp
 33 21     Awesome Artifacts.esp
 34 22     PrvtI_HeavyArmory.esp
 35 23     SL01AmuletsSkyrim.esp
 36 24     Dawnguard Sentries SE.esp
 37 25     Bring Out Your Dead.esp
 38 26     Immersive Patrols II.esp
 39 27     Bloodworm.esp
 40 28     Bells of Skyrim.esp
 41 29     Bells of Skyrim - Reduced Volume.esp
 42 2a     PrvtIRoyalArmory.esp
254 FE  19 DBM_RoyalArmory_Patch.esp
254 FE  1a LOTD_TCC_Royal.esp
254 FE  1b DBM_Wintersun_Patch.esp
254 FE  1c LOTD_TCC_Wintersun.esp
254 FE  1d DBM_AmuletsOfSkyrim_Patch.esp
254 FE  1e LOTD_TCC_Amulets.esp
 43 2b     Prometheus_BeastSkeletons.esp
254 FE  1f DBM_Undeath_Patch.esp
254 FE  20 LOTD_TCC_Undeath.esp
254 FE  21 DBM_CC_SaintsSeducersHOWPatch.esp
 44 2c     ForgottenCity.esp
254 FE  22 DBM_PathoftheRevanant_Patch.esp
254 FE  23 LOTD_TCC_PathRev.esp
254 FE  24 DBM_CC_GoblinsHOWPatch.esp
254 FE  25 LOTD_TCC_Goblins.esp
254 FE  26 DBM_CC_RareCuriosAddon04SaS.esp
254 FE  27 DBM_CC_StendarrsHammerHOWPatch.esp
254 FE  28 LOTD_TCC_StendarrsHammer.esp
254 FE  29 DBM_CC_Wilds01BackpacksHOWPatch.esp
254 FE  2a LOTD_TCC_Backpack.esp
 45 2d     Auroran Follower.esp
254 FE  2b DBM_TheGreatCitiesMinor_Patch.esp
 46 2e     Meridia's Champion Armor.esp
254 FE  2c LaFemmeLycana.esp
 47 2f     Believable Crime Report Radius.esp
 48 30     Growl - Werebeasts of Skyrim.esp
254 FE  2d NARC SE for Vanilla.esp
 49 31     DawnguardArsenal.esp
254 FE  2e Vigil Enforcer Distribution.esp
254 FE  2f NARC SE patch - Forgotten City.esp
 50 32     ArtifactsOfBoethiah.esp
254 FE  30 DBM_ArtifactsofBoethiah_Patch.esp
254 FE  31 LOTD_TCC_Boethiah.esp
254 FE  32 DBM_ForgottenCity_Patch.esp
254 FE  33 LOTD_TCC_TFC.esp
254 FE  34 DBM_CC_ShadowrendHOWPatchAoB.esp
254 FE  35 LOTD_TCC_Shadowrend_Boethiah.esp
254 FE  36 DBM_CC_ACArcaneArcherHOWPatch.esp
254 FE  37 LOTD_TCC_ArcaneArcher.esp
254 FE  38 DBM_HA_Patch.esp
254 FE  39 LOTD_TCC_HeavyArm.esp
254 FE  3a DBM_CC_RareCuriosAddon01PotD.esp
254 FE  3b DBM_CC_RareCuriosAddon03Gob.esp
254 FE  3c LOTD_TCC_Saints.esp
254 FE  3d DBM_CC_AADragonscaleHOWPatch.esp
254 FE  3e LOTD_TCC_AADragonscale.esp
254 FE  3f DBM_CC_AAEbonyPlateHOWPatch.esp
254 FE  40 LOTD_TCC_AAEbonyPlate.esp
254 FE  41 DBM_CC_AAStalhrimFurHOWPatch.esp
254 FE  42 LOTD_TCC_AAStalhrimFur.esp
254 FE  43 DBM_CC_AASteelSoldierHOWPatch.esp
254 FE  44 LOTD_TCC_AASteelSoldier.esp
254 FE  45 DBM_CC_ACPlagueOfTheDeadHOWPatch.esp
254 FE  46 LOTD_TCC_Plague.esp
254 FE  47 DBM_CC_RuinsEdgePatchV2.esp
254 FE  48 LOTD_TCC_RuinsEdgeCC.esp
254 FE  49 DBM_CC_StaffofSheogorathPatchV2.esp
254 FE  4a LOTD_TCC_StaffofSheoCC_Standalone.esp
254 FE  4b DBM_CC_Wilds03CampingHOWPatch.esp
254 FE  4c LOTD_TCC_Camping.esp
254 FE  4d DBM_DGA_Patch.esp
254 FE  4e LOTD_TCC_DawnguardArsenal.esp
254 FE  4f DBM_CC_ArmsOfChaosHOWPatch.esp
254 FE  50 LOTD_TCC_ArmsofChaos.esp
254 FE  51 DBM_CC_SpellKnightArmorHOWPatch.esp
254 FE  52 LOTD_TCC_SpellKnightArmor.esp
254 FE  53 DBM_CC_VigilEnforcerArmorHOWPatch.esp
254 FE  54 LOTD_TCC_VigilEnforcerArmorSet.esp
254 FE  55 DBM_CC_DwMudcrabHOWPatch.esp
254 FE  56 LOTD_TCC_DwarvenMudcrab.esp
254 FE  57 DBM_CC_RareCuriosAoBConsistencyPatch.esp
 51 33     Haem Projects Goblands.esp
254 FE  58 DragonCombatDialogue.esp
 52 34     SignatureEquipment.esp
 53 35     AHZmoreHUD.esp
 54 36     IcePenguinWorldMap.esp
 55 37     UndeadFX.esp
 56 38     UltimateCombat.esp
 57 39     SkyrimReputation_SSE.esp
 58 3a     MorePainfulNPCDeathSounds.esp
 59 3b     InstantMining.esp
 60 3c     Guard Dialogue Overhaul.esp
 61 3d     Ordinator - Perks of Skyrim.esp
254 FE  59 Ordinator - Beyond Skyrim Bruma Patch.esp
 62 3e     Sacrilege - Minimalistic Vampires of Skyrim.esp
 63 3f     Alternate Start - Live Another Life.esp
 64 40     DBM_RelicHunter.esp
 65 41     Immersive Citizens - AI Overhaul.esp
 66 42     Bells of Skyrim - ICAIO Patch.esp
 67 43     TheChoiceIsYours.esp
254 FE  5a BCS_TCIY_Patch.esp
 68 44     CFTO.esp
 69 45     CFTO - Immersive Citizens Patch.esp
254 FE  5b TCIY_Wintersun_Patch.esp
 70 46     Realistic AI Detection 2 SE Lite.esp

**Comment by Ic0nic0de** [comment]
Unable to reproduce this, perhaps post a crash log? TCC does not touch the fast travel system so highly likely another mod is causing this.

**Comment by bowem9** [comment]
I don't think it's actually the fast travel but rather the autosave that precedes it. I'm almost positive that attempting to save it what's causing the crashes but I'm not sure why. 
Here's my crash log:
[Papyrus.0.log](https://github.com/Ic0nic0de/TheCuratorsCompanion/files/5898699/Papyrus.0.log)

**Comment by Ic0nic0de** [comment]
No TCC errors and not able to reproduce
