### ISSUE TITLE
Continued Icon Issues

### ISSUE THREAD

**Issue by PineapplePez** [Ic0nic0de/TheCuratorsCompanion#18]
Hi,

I'm new to modding for context and I am having issues getting all icons in this mod to display (specifcally item cards/inventory) despite following the directions on the FAQ. Icons appear in the world as shown in attached files but not in inventory. I am not using iequip, as I know others have had issues. Apologies if simple fix and I am missing it. Thanks for any help.

![image](https://user-images.githubusercontent.com/80631207/111070850-9afff980-84a1-11eb-8103-b7310adc55da.png)
![image](https://user-images.githubusercontent.com/80631207/111070857-a4896180-84a1-11eb-955a-7d351c3b05e2.png)
![image](https://user-images.githubusercontent.com/80631207/111070896-c387f380-84a1-11eb-9f31-cfdfaaee84da.png)
[ModList.txt](https://github.com/Ic0nic0de/TheCuratorsCompanion/files/6136772/ModList.txt)

**Comment by Ic0nic0de** [comment]
Please go to the mcm and Select "Show All Icons" in the menu option on the moreHUD & Scan page

**Comment by PineapplePez** [comment]
Really appreciate the quick response! But I do have that checked.

![image](https://user-images.githubusercontent.com/80631207/111071542-a43e9580-84a4-11eb-89d9-4fec3543f7a9.png)

**Comment by Ic0nic0de** [comment]
can you go to debug options, click "Reset Startup tasks" then try again

**Comment by PineapplePez** [comment]
Unfortunately, that did not work either. I'm guessing there is a conflict somewhere that I just can't find?

**Comment by Ic0nic0de** [comment]
All I can suggest is reinstalling moreHUD IE from scratch, doesn't seem to be a TCC issue

**Comment by PineapplePez** [comment]
That worked! thank you so much for your time. I had originally tried "replacing" it, but completely deleting the mod and reinstalling from scratch did the trick. Thank you!
