### ISSUE TITLE
Stuck Scanning

### ISSUE THREAD

**Issue by MrGGFamily** [Ic0nic0de/TheCuratorsCompanion#20]
Been playing the Elysium for around 20 hours, and in that time have used the LotD museum a LOT, I always walk up to the "Display Drop Off" chest and dumping my shit. today however I get the following "The Curators Companion - Please wait for the current sort/scan operation to complete." and I have also lost all my icons of the museum items.  I have not made any changes to the pack. is there a way to maybe kill the scan and restart it?
Thanks

**Comment by Ic0nic0de** [comment]
Join the discord linked in the sticky post on Nexus please and i will talk you through the fix.
