### ISSUE TITLE
Agent of Righteous Might Compatibility Bug

### ISSUE THREAD

**Issue by GuavaaJuice** [Ic0nic0de/TheCuratorsCompanion#22]
In the questline of the mod Agent of Righteous Might, after the 2nd quest when you are prompted to turn in your gear for a job the menu for assigning this chest locks in place on the screen preventing loading, soft-locking progress. Reloading saves does not work and you are unable to select an option to make the menu go away.

**Comment by Ic0nic0de** [comment]
Remove token from inventory before activating the chest
