### ISSUE TITLE
TCC not correctly finding INIGO plugin

### ISSUE THREAD

**Issue by therealunrealcow** [Ic0nic0de/TheCuratorsCompanion#25]
I'm updating my version of TCC from 5.1.3 to 6.0.4.  I installed Inigo for the first time today (V 2.4C), so I'm expecting to be able to select Inigo under the FOMOD's Follower Display Add-ons, but it's greyed out.  The graphic that appears when hovering over Inigo suggests that it's expecting V 2.4C, which is the version of Inigo I've installed.  I've also confirmed the Inigo.esp is enabled in the Plugins tab of M02.

The FOMOD also has Vigilant, ESO Skyshards, and Moon and Star greyed out even though I have the latest versions of all of those enabled as well.

![image](https://user-images.githubusercontent.com/86990447/124525255-d3fb0b80-ddbb-11eb-847d-db9c9769a6b7.png)

**Comment by Benven99** [comment]
You need the Legacy Patches.

Vigilant and Moon & Star can be found in the main Legacy Patch page

Inigo can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/40816

ESO Skyshards can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/44915

**Comment by therealunrealcow** [comment]
Ah, many thanks.  I assumed any necessary patches would be included in the Legacy Patches FOMOD here: https://www.nexusmods.com/skyrimspecialedition/mods/30980

**Comment by Ic0nic0de** [comment]
Cheers Benven
