### ISSUE TITLE
Chimarvamidium duplicate items issue

### ISSUE THREAD

**Issue by googleben** [Ic0nic0de/TheCuratorsCompanion#28]
Chimarvamidium (Ancient Tales of the Dwemer part 6, displayed on the main floor of the library, left half, bottom shelf) is a special book in that there are two version of it (`0001AFF8` and `0001B22E`), and LOTD allows you to display either one, and only has one checkbox in its built-in checklist that gets checked regardless of which version you display. However, TCC only marks the version you displayed as completed, while the other version (though it may even be in the main stacks) is marked as uncollected. I suspect this is because of the way the book is listed in the forms. Its forms are listed in `DMB_LISTAncientTalesoftheDwemer` (`081387a2`), which is form 75 in `DBM_SsctionLibraryLowerFloorLeftItems` (`081387a1`).

Pictures showcasing the issue:
![image](https://user-images.githubusercontent.com/2458686/139790745-3ebf6682-6c76-48e2-bac0-88ec847bad6e.png)
![image](https://user-images.githubusercontent.com/2458686/139790821-6e7ceec6-c6b5-4685-83b0-68166cd0254b.png)

**Comment by N9is** [comment]
Exclusive displays are hard for TCC to deal with. Thankfully for this one you can circumvent it.
Remove the book set and re-place the set when you have both Chimarvamidiums in your inventory. The display will take both if you have them but will not take the other one if one is already placed.

**Comment by googleben** [comment]
Just commenting to confirm that workaround did the trick for me as a temporary fix.

**Comment by Ic0nic0de** [comment]
I have a process checking for replicas etc but to do script work for every single display that supports multiple items would be a nightmare, I may sort this book out specifically as it’s been raised before but for now just ignore the other icon as you know you have it on display.
