### ISSUE TITLE
Mismatching name of mods between esp and patchs

### ISSUE THREAD

**Issue by Irwine** [Ic0nic0de/TheCuratorsCompanion#4]
There is an issue between the main esp and the following CC patch 
The names of the mods are different.

In the main esp the names are:

Alternative Armors - Daedric Mail
Alternative Armors - Dragonscale
Alternative Armors - Dwarven Mail
Alternative Armors - Ebony Plate
Alternative Armors - Elven Hunter
Alternative Armors - Stalhrim Fur
Alternative Armors - Steel Soldier

In the patch the names are :

Alternate Armors - Daedric Mail
Alternate Armors - Dragonscale
Alternate Armors - Dwarven Mail
Alternate Armors - Ebony Plate
Alternate Armors - Elven Hunter
Alternate Armors - Stalhrim Fur
The Curators Companion - Alternate Armors - Steel Soldier

I'm speaking of about vmad record in both main esp and patchs

**Comment by Ic0nic0de** [comment]
Fixed, Thanks for the report.
