### ISSUE TITLE
Wrong title/name CC DeadMansDread_OAP, CC StendarrsHammer

### ISSUE THREAD

**Issue by Irwine** [Ic0nic0de/TheCuratorsCompanion#5]
In this patch the entry that's should contain the name of the patch is wrong

Actually it's : Dead Man's Dread - Arcane Accessories
It should be : The Curators Companion - Dead Man's Dread

The data of this entry are :
QUST | 0C000804 | TCC_SM_DeadMansDread | FULL

**Comment by Ic0nic0de** [comment]
Fixed Thanks

**Comment by Irwine** [comment]
There is the same issue in CC StendarrsHammer patch : 

It's : Museum Scanner: Set Complete (Stendarr's Hammer)
It should be : The Curators Companion - Stendarr's Hammer

QUST | 0A000804 | TCC_SM_StendarrsHammer | FULL |
